### ISSUE TITLE
Agent does not provide access to http responce headers.

### ISSUE THREAD

**Issue by chinaryov** [ic4j/ic4j-agent#1]
Hello!

Is it possible somehow get access to http response headers?
For example - there are headers in the response from IC:

```
Server: nginx/1.21.3
Date: Thu, 26 May 2022 11:51:07 GMT
Content-Type: application/cbor
Content-Length: 460009
Connection: keep-alive
x-ic-subnet-id: brlsh-zidhj-3yy3e-6vqbz-7xnih-xeq2l-as5oc-g32c4-i5pdn-2wwof-oae
x-ic-node-id: tmugi-2ynno-fdkdg-x7dk6-mzbe7-3vsgh-khnw7-qdq4s-s5cz7-zsxko-6qe
x-ic-canister-id: 00000000010012560101
access-control-allow-methods: POST, GET
access-control-allow-origin: *
access-control-allow-headers: Accept, Authorization, Content-Type
X-Content-Type-Options: nosniff
content-type: application/cbor
```
In our application we are using next headers:
```
x-ic-subnet-id: brlsh-zidhj-3yy3e-6vqbz-7xnih-xeq2l-as5oc-g32c4-i5pdn-2wwof-oae
x-ic-node-id: tmugi-2ynno-fdkdg-x7dk6-mzbe7-3vsgh-khnw7-qdq4s-s5cz7-zsxko-6qe
x-ic-canister-id: 00000000010012560101
```
These headers are available in the class ReplicaApacheHttpTransport but it is far away from Agent. I do not see any simple change I would make locally to get access to it.

Thank you in advance.

Best regards,
Alexander

**Comment by rdobrik** [comment]
Yes, that is very valid scenario. We can somehow expose inbound and outbound headers. Just need to think about API. Make it protocol agnostic, if eventually we will support other than HTTP protocols.I can add initially some support to raw methods. Let me think about it, I can build some API mock up, and share it with you.

**Comment by chinaryov** [comment]
Thank you. I am ready for testing it.

**Comment by rdobrik** [comment]
I redesigned Agent and transports to support request and response headers. Now you can use Response wrapper object with getPayload and getHeaders functions. getPayload returns binary byte[] value so you have to do deserialization on your own after call. Request headers are there too, just in case if we need them in the future. I checked in the code, but did not make official build on Maven Central yet, this is major redesign, so I want to run more tests over weekend, then have Agent Release Candidate out. Probably tomorrow or Monday.
Response with headers can be used with raw methods, Query and Update builders and ProxyBuilder as well.
Check ICTest to see some use cases for raw methods. I need to write more unit test for Builders scenarios.

**Comment by rdobrik** [comment]
Release Candidate 12 with header support is out. Tested with different Replica Transports, Apache, OkHttp, native Java 11 agent.

**Comment by chinaryov** [comment]
I just did migrationt to the newest version - org.ic4j ic4j-candid 0.6.12
For me it is good enough. Thank you.

One question. I am working with many canisters. What is a good way to close/release agent/transport layer?
Http transport uses closeable http client but it is not accessable outside of IMPL at the moment.

**Comment by rdobrik** [comment]
Let me check. I can implement such function in the next release.

**Comment by chinaryov** [comment]
Thank you. it would be great.
